<nav class="pt-2" style="position: sticky; top: 0; min-height: 100vh; overflow: auto">
   <h6 class="text-uppercase px-3 mt-4 mb-1 text-muted">
      Management
   </h6>
   <ul class="nav flex-column mb-2">
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-folder2-open"></i>
            Sections
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-camera"></i>
            Media
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-people"></i>
            Users
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-gear"></i>
            Settings
         </a>
      </li>
   </ul>
</nav>