<nav class="pt-2" style="position: sticky; top: 0; min-height: 100vh; overflow: auto">
   <h6 class="text-uppercase px-3 mt-4 mb-1 text-muted">
      Content
   </h6>
   <ul class="nav flex-column mb-2">
      <li class="nav-item">
         <a class="nav-link text-dark" href="/user/account">
            <i class="bi bi-house-door"></i>
            Overview
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="/user/posts">
            <i class="bi bi-file-richtext"></i>
            Articles
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="/user/comments">
            <i class="bi bi-chat-square-text"></i>
            Comments
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-person"></i>
            Account
         </a>
      </li>
   </ul>
   <h6 class="text-uppercase px-3 mt-4 mb-1 text-muted">
      Management
   </h6>
   <ul class="nav flex-column mb-2">
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-folder2-open"></i>
            Sections
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-camera"></i>
            Media
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-people"></i>
            Users
         </a>
      </li>
      <li class="nav-item">
         <a class="nav-link text-dark" href="#">
            <i class="bi bi-gear"></i>
            Settings
         </a>
      </li>
   </ul>
</nav>