<?= $this->layout('Layouts/layout') ?>
<div class="container-fluid">
	<div class="row">
		<nav style="width: 250px; min-height: 100vh; background-color: #f0f4f7;">
			<h6 class="text-uppercase px-3 mt-4 mb-1 text-muted">
				User
			</h6>
			<ul class="nav flex-column mb-2">
				<li class="nav-item">
					<a class="nav-link text-dark" href="#">
						<i class="bi bi-person"></i>
						Profile
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" href="#">
						<i class="bi bi-envelope"></i>
						Messages
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" href="#">
						<i class="bi bi-bell"></i>
						Notifications
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" href="#">
						<i class="bi bi-gear"></i>
						Settings
					</a>
				</li>
			</ul>
			<h6 class="text-uppercase px-3 mt-4 mb-1 text-muted">
				Content
			</h6>
			<ul class="nav flex-column mb-2">
				<li class="nav-item">
					<a class="nav-link text-dark" href="#">
					<i class="bi bi-file-richtext"></i>
						Articles
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" href="#">
						<i class="bi bi-chat-square-text"></i>
						Comments
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" href="#">
						<i class="bi bi-folder2-open"></i>
						Categories
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" href="#">
						<i class="bi bi-images"></i>
						Media
					</a>
				</li>
			</ul>
		</nav>
		<div class="d-flex flex-grow-1 flex-column justify-content-center text-center" style="height: 400px; width: 400px">
			<h1 class="text-info display-3 mx-auto">Hello!</h1>
			<h6 class="text-info display-6 mx-auto"><?= $this->ViewData['Email'] ?></h6>
			<p class="lead">Click on the log out button to close your session.</p>
			<a class="btn btn-info text-white mx-auto" href="/account/logout">Log Out</a>
		</div>
	</div>
</div>
