<?= $this->layout('Shared/Layout') ?>

<!-- Include stylesheet -->
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

<div class="container-fluid" style="background-color: #f0f4f7;">
   <div class="row">
      <aside class="bg-white" style="width: 200px;">
         <?= $this->renderPartial('Shared/UserSidebar') ?>
      </aside>
      <div class="d-flex flex-grow-1 flex-column px-4 py-3" style="min-height: 400px; width: 400px">
         <header class="my-3">
            <h3 class="text-uppercase">new Article</h3>
         </header>
         <form method="post" action="/user/posts/new">
            <div class="row">
               <div class="col-md-9 mb-3">
                  <select name="Status" class="form-select" style="width: 230px;">
                     <option value="1">Draft</option>
                     <option value="2">Published</option>
                     <option value="3">Archived</option>
                  </select>
               </div>
               <div class="col-md-3 text-end mb-3">
                  <button type="submit" class="btn btn-primary" style="height: 38px; width: 49%"><i class="bi bi-check-lg me-1"></i>Save</button>
                  <a class="btn btn-secondary" href="/user/posts" style="height: 38px; width: 49%"><i class="bi bi-x-lg me-1"></i>Cancel</a>
               </div>
            </div>
            <div class="row">
               <div class="col-md-9">
                  <div class="card mb-3">
                     <div class="card-body p-4">
                        <div class="mb-3">
                           <label for="title" class="form-label">Title</label>
                           <input type="text" class="form-control" id="title" name="Title">
                        </div>
                        <div class="mb-1">
                           <label for="content" class="form-label">Content</label>
                           <textarea id="content" name="Content" style="display: none;"></textarea>
                           <div id="editor" style="height: 325px;"></div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-md-3">
                  <div class="card mb-3">
                     <div class="card-header">
                        Permalink
                     </div>
                     <div class="card-body">
                        <div class="mb-3">
                           <input type="text" class="form-control" id="slug" name="Slug">
                        </div>
                     </div>
                  </div>
                  <div class="card mb-3">
                     <div class="card-header">
                        Section
                     </div>
                     <div class="card-body">
                        <select class="form-select" id="section" name="Section">
                           <option value="1">Events</option>
                           <option value="2">News</option>
                           <option value="3">Trending</option>
                        </select>
                     </div>
                  </div>
                  <div class="card mb-3">
                     <div class="card-header">
                        Image
                     </div>
                     <div class="card-body">
                        <div class="input-group">
                           <input type="text" class="form-control" id="image" name="Image" aria-label="Recipient's username" aria-describedby="button-addon">
                           <button type="button" class="btn btn-outline-secondary" id="open">Open</button>
                        </div>
                     </div>
                  </div>
                  <div class="card mb-3">
                     <div class="card-header">
                        Excerpt
                     </div>
                     <div class="card-body">
                        <textarea class="form-control" id="excerpt" name="Excerpt" rows="3"></textarea>
                     </div>
                  </div>
               </div>
            </div>
         </form>
      </div>
   </div>
</div>

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
   var toolbarOptions = [
      [{
         'font': []
      }],
      [{
         'header': [1, 2, 3, 4, 5, 6, false]
      }],
      ['bold', 'italic', 'underline', 'strike'], // toggled buttons
      [{
         'color': []
      }, {
         'background': []
      }], // dropdown with defaults from theme
      [{
         'script': 'sub'
      }, {
         'script': 'super'
      }], // superscript/subscript
      [{
         'list': 'ordered'
      }, {
         'list': 'bullet'
      }],
      [{
         'direction': 'rtl'
      }, , {
         'align': []
      }], // text direction
      ['blockquote', 'code-block'],
      ['clean'] // remove formatting button
   ];

   var quill = new Quill('#editor', {
      modules: {
         toolbar: toolbarOptions
      },
      theme: 'snow'
   });

   quill.on('text-change', update);
   update();

   function update() {
      var content = document.querySelector('#content');
      content.innerHTML = quill.root.innerHTML;
   }

   var title = document.getElementById('title');
   title.onchange = function() {
      var slug = document.getElementById('slug');
      slug.value = title.value.replace(/ /g, '-');
   }

   var open = document.getElementById('open');
   open.onclick = function() {
      var input = document.createElement('input');
      input.type = 'file';
      input.onchange = function() {
         var files = Array.from(input.files);
         var image = document.getElementById('image');
         image.value = files[0].name;
      };
      input.click();
   }
</script>