<?= $this->layout('Shared/Layout') ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 430px; background-image: url(/images/4-800x200.jpg); background-size: cover;">
   <h1 class="text-warning display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;">Welcome</h1>
   <p class="lead w-75 mx-auto text-white fw-normal" style="text-shadow: 2px 2px 8px #000;">To a modern lightweight PHP framework inspired by ASP.NET Core</p>
   <a class="btn btn-danger text-white mx-auto" href="https://devnet-framework.github.io">Read more</a>
</div>
<!-- Newsletter -->
<div class="p-4">
   <div class="container">
      <div class="row align-items-center p-lg-3">
         <div class="col-lg-6 mb-4 mb-lg-0">
            <h4 class="mb-1">Subscribe to newsletter</h4>
            <p class="mb-0 text-small">
               Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            </p>
         </div>
         <div class="col-lg-6">
            <form action="#">
               <div class="input-group">
                  <input class="form-control" type="search" placeholder="Enter your email address" aria-label="email address" aria-describedby="button-addon2">
                  <div class="input-group-append ml-2">
                     <button class="btn btn-danger" id="button-addon2" type="submit">Subscribe</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
<!-- /Newsletter -->
<!-- Blog Sections -->
<section class="text-center bg-light">
   <br><br>
   <div class="container">
      <h2 class="text-uppercase text-dark">Sections</h2>
      <p>
         Browse our classified Blog Sections
      </p>
      <br>
      <div class="row row-cols-1 row-cols-md-3 g-4">
         <?php foreach ($this->ViewData['sections'] as $section) : ?>
            <div class="col">
               <div class="card shadow-sm h-100">
                  <div class="card-body d-flex flex-column justify-content-center">
                     <h5 class="card-title"><?= $section->Title ?></h5>
                     <p class="card-text">
                        <?= $section->Description ?>
                     </p>
                  </div>
                  <a class="btn btn-danger text-white mx-auto mb-4" href="/blog/section/<?= $section->Id ?>">
                     View Blogs</a>
               </div>
            </div>
         <?php endforeach ?>
      </div>
      <br><br><br>
</section>
<!-- /Blog Sections -->
<!-- Featured carousel -->
<div class="container">
   <br><br>
   <h2 class="text-uppercase text-center">Featured Articles</h2>
   <p class="text-center">
      Lorem ipsum dolor sit amet consectetur adipisicing elit.
   </p>
   <br>
   <div id="featuredcarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
         <?php for ($i = 0; $i < count($this->ViewData['featured']); $i++) : ?>
            <?php if ($i == 0) : ?> <div class="carousel-item active">
               <?php else : ?> <div class="carousel-item">
                  <?php endif ?>
                  <div class="card mb-3 border-0" style="background-color: #f8f9fa;">
                     <a class="text-decoration-none text-dark" href="/blog/post/<?= $this->ViewData['featured'][$i]->Id ?>">
                        <div class="row g-0">
                           <div class="col-md-6">
                              <img class="img-fluid w-100 h-100" src="/images/post/<?= $this->ViewData['featured'][$i]->Image ?>" alt="...">
                           </div>
                           <div class="col-md-6">
                              <div class="card-body p-5">
                                 <p class="card-text">
                                    <small class="text-muted text-uppercase">Editor's Pick</small>
                                 </p>
                                 <h4 class="card-title"><?= $this->ViewData['featured'][$i]->Title ?></h4>
                                 <p class="card-text">
                                    <small class="text-muted">On <?= $this->ViewData['featured'][$i]->EditedAt ?> | By Author Id
                                       <?= $this->ViewData['featured'][$i]->AuthorId ?></small>
                                 </p>
                                 <p class="card-text">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe magnam repellat repellendus, nostrum est ratione, consequuntur officia, itaque porro velit distinctio beatae vero obcaecati labore quibusdam tenetur tempora sit animi.
                                 </p>
                              </div>
                           </div>
                        </div>
                     </a>
                  </div>
                  </div>
               <?php endfor ?>
               </div>
      </div>
   </div>
   <!-- /Featured carousel -->

   <!-- Recent Articles -->
   <section class="bg-light">
      <div class="container">
         <br><br>
         <h2 class="text-uppercase text-center">Recent Articles</h2>
         <p class="text-center">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
         </p>
         <br>
         <div class="row row-cols-1 row-cols-md-3 g-4">
            <?php foreach ($this->ViewData['recents'] as $recent) : ?>
               <div class="col">
                  <a class="text-decoration-none text-dark" href="/blog/post/<?= $recent->Id ?>">
                     <div class="card h-100">
                        <img class="img-fluid" src="/images/post/<?= $recent->Image ?>" alt="...">
                        <div class="card-body">
                           <h5 class="card-title"><?= $recent->Title ?></h5>
                           <p class="card-text">
                              <small class="text-muted">On <?= $recent->EditedAt ?> | By <?= $recent->AuthorId ?></small>
                           </p>
                           <p class="card-text">
                              <?= $recent->Content ?> </p>
                        </div>
                     </div>
                  </a> </div> <?php endforeach ?>
         </div>
         <br><br>
      </div>
   </section>
   <!-- /Recent Articles -->