<?= $this->layout('layouts/layout') ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 420px; background-image: url(https://picsum.photos/id/4/800/200); background-size: cover;">
   <h1 class="text-danger display-2 mx-auto">Welcome</h1>
   <p class="lead w-75 mx-auto text-white">To a modern lightweight PHP framework inspired by ASP.NET Core</p>
   <a class="btn btn-danger text-white mx-auto" href="https://devnet-framework.github.io">Read more</a>
</div>
<!-- Newsletter -->
<div class="p-4">
   <div class="container">
      <div class="row align-items-center p-lg-3">
         <div class="col-lg-6 mb-4 mb-lg-0">
            <h4 class="mb-1">Subscribe to newsletter</h4>
            <p class="mb-0 text-small">
               Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            </p>
         </div>
         <div class="col-lg-6">
            <form action="#">
               <div class="input-group">
               <input class="form-control" type="search" placeholder="Enter your email address" aria-label="email address" aria-describedby="button-addon2">
               <div class="input-group-append ml-2">
                  <button class="btn btn-danger" id="button-addon2" type="submit">Subscribe</button>
               </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
<!-- /Newsletter -->
<!-- Blog Sections -->
<section class="text-center bg-light">
   <br><br>
   <div class="container">
      <h2 class="text-uppercase text-dark">Sections</h2>
      <p>
         Browse our classified Blog Sections
      </p>
      <br>
      <div class="row row-cols-1 row-cols-md-3 g-4">
         <div class="col">
            <div class="card shadow-sm h-100">
               <div class="card-body d-flex flex-column justify-content-center">
                  <h5 class="card-title">News</h5>
                  <p class="card-text">
                     Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                  </p>
               </div>
            </div>
         </div>
      <div class="col">
         <div class="card shadow-sm h-100">
            <div class="card-body d-flex flex-column justify-content-center">
               <h5 class="card-title">Events</h5>
               <p class="card-text">
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit.
               </p>
            </div>
         </div>
      </div>
      <div class="col">
         <div class="card shadow-sm h-100">
            <div class="card-body d-flex flex-column justify-content-center">
               <h5 class="card-title">Trending</h5>
               <p class="card-text">
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit.
               </p>
            </div>
         </div>
      </div>
   </div>
   <br><br><br>
</section>
<!-- /Blog Sections -->
<!-- Featured Articles -->
<section>
   <div class="container">
      <br><br>
      <h2 class="text-uppercase text-center">Featured Articles</h2>
      <p class="text-center">
         Lorem ipsum dolor sit amet consectetur adipisicing elit.
      </p>
      <br>
      <div class="card mb-3 border-0" style="background-color: #f8f9fa;">
         <div class="row g-0">
            <div class="col-md-6">
               <img class="img-fluid w-100 h-100" src="https://picsum.photos/id/326/500/300" alt="...">
            </div>
            <div class="col-md-6">
               <div class="card-body p-5">
                  <p class="card-text">
                     <small class="text-muted text-uppercase">Editor's Pick</small>
                  </p>
                  <h4 class="card-title">Featured Article Title</h4>
                  <p class="card-text">
                     <small class="text-muted">On February 23, 2019 | By john doe</small>
                  </p>
                  <p class="card-text">
                     Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe magnam repellat repellendus, nostrum est ratione, consequuntur officia, itaque porro velit distinctio beatae vero obcaecati labore quibusdam tenetur tempora sit animi.
                  </p>
               </div>
            </div>
         </div>
      </div>
      <br><br>
   </div>
</section>
<!-- /Featured Articles -->
<!-- Recent Articles -->
<section class="bg-light">
   <div class="container">
      <br><br>
      <h2 class="text-uppercase text-center">Recent Articles</h2>
      <p class="text-center">
         Lorem ipsum dolor sit amet consectetur adipisicing elit.
      </p>
      <br>
      <div class="row row-cols-1 row-cols-md-3 g-4">
         <div class="col">
            <div class="card h-100">
               <img class="img-fluid" src="https://picsum.photos/id/365/300/200" alt="...">
               <div class="card-body">
                  <h5 class="card-title">Post title</h5>
                  <p class="card-text">
                     <small class="text-muted">On February 23, 2019 | By john doe</small>
                  </p>
                  <p class="card-text">
                     Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores iure, delectus minus facere similique laudantium praesentium! Neque eligendi consectetur quo repellendus ipsam sapiente mollitia optio quas pariatur perferendis. Hic, optio!
                  </p>
               </div>
            </div>
         </div>
         <div class="col">
            <div class="card h-100">
               <img class="img-fluid" src="https://picsum.photos/id/401/300/200" alt="...">
               <div class="card-body">
                  <h5 class="card-title">Post title</h5>
                  <p class="card-text">
                     <small class="text-muted">On February 23, 2019 | By john doe</small>
                  </p>
                  <p class="card-text">
                     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quae, enim. Magnam veritatis, aut tenetur pariatur dignissimos neque. Praesentium temporibus, vitae provident id esse, corporis dolorum sapiente impedit culpa eum fuga.
                  </p>
               </div>
            </div>
         </div>
         <div class="col">
            <div class="card h-100">
               <img class="img-fluid" src="https://picsum.photos/id/425/300/200" alt="...">
               <div class="card-body">
                  <h5 class="card-title">Post title</h5>
                  <p class="card-text">
                     <small class="text-muted">On February 23, 2019 | By john doe</small>
                  </p>
                  <p class="card-text">
                     Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vel deserunt debitis possimus. Recusandae, soluta officia. Pariatur similique quasi fugiat quis nam quam esse inventore praesentium soluta, nihil, suscipit cum aperiam!
                  </p>
               </div>
            </div>
         </div>
      </div>
      <br><br>
   </div>
</section>
<!-- /Recent Articles -->
