<?= $this->layout('Layouts/Layout') ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 250px; background-image: url(https://picsum.photos/id/113/800/200); background-size: cover;">
   <h1 class="text-info display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;">Our Blog</h1>
   <p class="lead w-75 mx-auto text-white fw-normal" style="text-shadow: 2px 2px 8px #000;">Will keep you updated</p>
</div>
<div class="container">
   <br><br>
   <div class="row">
      <div class="col-md-8">
         <a class="text-decoration-none text-dark" href="/blog/post">
            <div class="card mb-3 shadow-sm">
               <div class="row g-0">
                  <div class="col-md-5">
                     <img class="img-fluid w-100 h-100" src="https://picsum.photos/id/365/300/200" alt="...">
                  </div>
                  <div class="col-md-7">
                     <div class="card-body">
                        <h5 class="card-title">Post title</h5>
                        <p class="card-text">
                           <small class="text-muted">On February 23, 2019 | By john doe</small>
                        </p>
                        <p class="card-text">
                           Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores iure, delectus minus facere similique laudantium praesentium! Neque eligendi consectetur quo repellendus ipsam sapiente mollitia optio quas pariatur perferendis. Hic, optio!
                        </p>
                     </div>
                  </div>
               </div>
            </div>
         </a>
         <a class="text-decoration-none text-dark" href="/blog/post">
            <div class="card mb-3 shadow-sm">
               <div class="row g-0">
                  <div class="col-md-5">
                     <img class="img-fluid w-100 h-100" src="https://picsum.photos/id/401/300/200" alt="...">
                  </div>
                  <div class="col-md-7">
                     <div class="card-body">
                        <h5 class="card-title">Post title</h5>
                        <p class="card-text">
                           <small class="text-muted">On February 23, 2019 | By john doe</small>
                        </p>
                        <p class="card-text">
                           Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quae, enim. Magnam veritatis, aut tenetur pariatur dignissimos neque. Praesentium temporibus, vitae provident id esse, corporis dolorum sapiente impedit culpa eum fuga.
                        </p>
                     </div>
                  </div>
               </div>
            </div>
         </a>
         <a class="text-decoration-none text-dark" href="/blog/post">
            <div class="card mb-3 shadow-sm">
               <div class="row g-0">
                  <div class="col-md-5">
                     <img class="img-fluid w-100 h-100" src="https://picsum.photos/id/425/300/200" alt="...">
                  </div>
                  <div class="col-md-7">
                     <div class="card-body">
                        <h5 class="card-title">Post title</h5>
                        <p class="card-text">
                           <small class="text-muted">On February 23, 2019 | By john doe</small>
                        </p>
                        <p class="card-text">
                           Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vel deserunt debitis possimus. Recusandae, soluta officia. Pariatur similique quasi fugiat quis nam quam esse inventore praesentium soluta, nihil, suscipit cum aperiam!
                        </p>
                     </div>
                  </div>
               </div>
            </div>
         </a>
         <nav class="blog-pagination" aria-label="Pagination">
            <a class="btn btn-outline-primary" href="#">Older</a>
            <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
         </nav>
         <br>
      </div>
      <div class="col-md-4">
         <aside class="px-3 pb-3">
            <form action="#">
               <div class="input-group">
               <input class="form-control" type="search" placeholder="Enter your email address" aria-label="email address" aria-describedby="button-addon2">
               <div class="input-group-append ml-2">
                  <button class="btn btn-danger" id="button-addon2" type="submit">Subscribe</button>
               </div>
               </div>
            </form>
         </aside>
         <aside class="p-3">
            <h6 class="text-uppercase mb-1 text-muted">
               Follow Us
            </h6>
            <ul class="nav flex-column mb-2">
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-facebook fs-5 lh-1"></i>
                     Facebook
                  </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-twitter fs-5 lh-1"></i>
                     Twitter
                  </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-youtube fs-5 lh-1"></i>
                     Youtube
                  </a>
               </li>
            </ul>
         </aside>
         <aside class="p-3">
            <h6 class="text-uppercase mb-1 text-muted">
               Sections
            </h6>
            <ul class="nav flex-column mb-2">
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-folder2-open lh-1"></i>
                     News
                  </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-folder2-open lh-1"></i>
                     Events
                  </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-folder2-open lh-1"></i>
                     Ternding
                  </a>
               </li>
            </ul>
         </aside>
         <aside class="p-3">
            <h6 class="text-uppercase mb-2 text-muted">
               Recent Comments
            </h6>
            <ul class="nav flex-column mb-2">
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                  <i class="bi bi-chat-text"></i>
                     Lorem ipsum dolor sit amet consectetur adipisicing elit...
                  </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-chat-text"></i>
                     Lorem ipsum dolor sit amet consectetur adipisicing elit...
                  </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-chat-text"></i>
                     Lorem ipsum dolor sit amet consectetur adipisicing elit...
                  </a>
               </li>
            </ul>
         </aside>
      </div>
   </div>
</div>