<?= $this->layout('Shared/Layout') ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 250px; background-image: url(/images/113-800x200.jpg); background-size: cover;">
   <h1 class="text-info display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;">Our Blog</h1>
   <p class="lead w-75 mx-auto text-white fw-normal" style="text-shadow: 2px 2px 8px #000;">Will keep you updated</p>
</div>
<div class="container">
   <br><br>
   <div class="row">
      <div class="col-md-8">
         <?php foreach ($this->ViewData['posts'] as $post) : ?>
            <a class="text-decoration-none text-dark" href="/blog/post/<?= $post->Id ?>">
               <div class="card mb-3 shadow-sm">
                  <div class="row g-0">
                     <div class="col-md-5">
                        <img class="img-fluid w-100 h-100" src="/images/post/<?= $post->Image ?>" alt="...">
                     </div>
                     <div class="col-md-7">
                        <div class="card-body">
                           <h5 class="card-title"><?= $post->Title ?></h5>
                           <p class="card-text">
                              <small class="text-muted">On February 23, 2019 | By john doe</small>
                           </p>
                           <p class="card-text">
                              <?= $post->Excerpt ?>
                           </p>
                        </div>
                     </div>
                  </div>
               </div>
            </a>
         <?php endforeach ?>
         <nav class="blog-pagination" aria-label="Pagination">
            <a class="btn btn-outline-primary" href='/blog/page/<?= $this->ViewData['page'] + 1 ?>'>Older</a>
            <a class="btn btn-outline-secondary" href='/blog/page/<?= $this->ViewData['page'] - 1 ?>' tabindex="-1" aria-disabled="true">Newer</a>
         </nav>
         <br>

      </div>
      <div class="col-md-4">
         <?= $this->renderPartial('Shared/Sidebar') ?>
      </div>
   </div>
</div>