<?= $this->layout('Shared/Layout') ?>
//---------------
<div class="d-flex flex-column justify-content-center text-center" style="height: 250px; background-image: url(https://picsum.photos/id/113/800/200); background-size: cover;">
   <h1 class="text-info display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;">
      <h1 class="text-info display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;"><?= $model->Title ?></h1>
      <p class="lead w-75 mx-auto text-white fw-normal" style="text-shadow: 2px 2px 8px #000;">
         By <?= $model->Author->Name ?> | On <?= $model->EditedAt ?>
      </p>
</div>
<div class="container">
   <br><br>
   <div class="row">
      <div class="col-md-8">
         <article>
            <nav aria-label="breadcrumb">
               <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="/">Home</a></li>
                  <li class="breadcrumb-item"><a href="/home/blog">Blog</a></li>
                  <li class="breadcrumb-item active" aria-current="page"><?= $model->Title ?></li>
               </ol>
            </nav>
            <small class="text-muted">By <?= $model->Author->Name ?> | On February 23, 2019</small>
            <p class="fst-italic">
               Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores iure, delectus minus facere similique laudantium praesentium! Neque eligendi consectetur quo repellendus ipsam sapiente mollitia optio quas pariatur perferendis. Hic, optio!
            </p>
            <div class="bg-light p-5 rounded">
               <h1>Thumbnail example</h1>
               <p class="lead">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis cumque aliquid et est labore eaque similique perferendis a quo, corrupti consequatur voluptate mollitia, voluptatum nihil. Nostrum nesciunt earum iusto eos?
               </p>
            </div>
            <br>
            <p>
               Lorem ipsum dolor sit amet consectetur adipisicing elit. At doloremque deserunt magnam nulla ab delectus, vero rem ad, corrupti qui iure rerum pariatur ea aperiam. Numquam aut ratione a autem.
            </p>
            <p>
               Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum perferendis fuga maxime, neque ipsum doloremque perspiciatis, praesentium quos incidunt doloribus odio! Pariatur cum fuga quos! Sit voluptatem pariatur perspiciatis hic!
            </p>
            <p>
               Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto dicta a, eius sapiente ea quaerat, sequi minus ipsa totam ratione adipisci fuga excepturi, dolores delectus placeat tempore. Incidunt, fuga praesentium?
            </p>
            <aside>
               <div>
                  <h4>Comments</h4>
                  <form method="post" action="/user/comment/new/<?= $model->Id ?>">
                     <textarea class="form-control h-100" id="message" name="Message" placeholder="Your Comment *" onfocus="show(true)" required=""></textarea>
                     <button type="submit" class="btn btn-info text-white" id="send">Send</button>

                  </form>
                  <br>
                  <?php foreach (array_reverse($model->Comments->toArray()) as $comment) : ?>
                     <!-----  <h6><= $comment->Author->Name ?></h6>  ---->
                     <div class="row fs-6 lh-sm">
                        <div class="col-1">
                           <img class="img-fluid rounded-circle" src="<?= $comment->Author->Photo ?>" alt="">
                        </div>
                        <div class="col-11">
                           <p class="fs-6 lh-sm">
                              <b><?= $comment->Author->Name ?></b><span><small> | on <?= $comment->EditedAt ?></small></span>
                              <br>
                              <small><?= $comment->Content ?></small>
                           </p>
                        </div>
                     </div>

                  <?php endforeach ?>
               </div>
            </aside>
         </article>
         <br>
      </div>
      <div class="col-md-4">
         <aside class="px-3 pb-3">
            <form action="#">
               <div class="input-group">
                  <input class="form-control" type="search" placeholder="Enter your email address" aria-label="email address" aria-describedby="button-addon2">
                  <div class="input-group-append ml-2">
                     <button class="btn btn-danger" id="button-addon2" type="submit">Subscribe</button>
                  </div>
               </div>
            </form>
         </aside>
         <aside class="p-3">
            <h6 class="text-uppercase mb-1 text-muted">
               Follow Us
            </h6>
            <ul class="nav flex-column mb-2">
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-facebook fs-5 lh-1"></i>
                     Facebook
                  </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-twitter fs-5 lh-1"></i>
                     Twitter
                  </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link text-dark border-bottom" href="#">
                     <i class="bi bi-youtube fs-5 lh-1"></i>
                     Youtube
                  </a>
               </li>
            </ul>
         </aside>
         <aside class="p-3">
            <h6 class="text-uppercase mb-1 text-muted">
               Sections
            </h6>
            <ul class="nav flex-column mb-2">
               <?php foreach ($this->ViewData['sections'] as $section) : ?>
                  <li class="nav-item">
                     <a class="nav-link text-dark border-bottom" href="/home/section/<?= $section->Id ?>">
                        <i class="bi bi-folder2-open lh-1"></i>
                        <?= $section->Title ?>
                     </a>
                  </li>
               <?php endforeach ?>
            </ul>
         </aside>
         <aside class="p-3">
            <h6 class="text-uppercase mb-2 text-muted">
               All Recent Comments
            </h6>
            <ul class="nav flex-column mb-2">
               <?php foreach ($this->ViewData['comments'] as $comment) : ?>
                  <!-----  <h6><= $comment->Author->Name ?></h6>  ---->
                  <div class="row fs-6 lh-sm">
                     <p class="fs-6 lh-sm">
                        <span><small> <b><?= $comment->EditedAt ?></b></small></span>
                        <br>
                        <i class="bi bi-chat-left-text"></i>
                        <small><?= $comment->Content ?></small>
                        <br>
                        <small><a href="">Read more</a></small>
                     </p>
                  </div>
               <?php endforeach ?>
            </ul>
         </aside>
      </div>
   </div>
</div>
//-------------

<div class="d-flex flex-column justify-content-center text-center" style="height: 250px; background-image: url(https://picsum.photos/id/113/800/200); background-size: cover;">
   <h1 class="text-info display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;">Post Tilte</h1>
   <p class="lead w-75 mx-auto text-white fw-normal" style="text-shadow: 2px 2px 8px #000;">
      By john doe | On February 23, 2019
   </p>
</div>
<div class="container">
   <br><br>
   <div class="row">
      <div class="col-md-8">
         <article>
            <nav aria-label="breadcrumb">
               <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="/">Home</a></li>
                  <li class="breadcrumb-item"><a href="/blog">Blog</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Post Title</li>
               </ol>
            </nav>
            <small class="text-muted">By john doe | On February 23, 2019</small>
            <p class="fst-italic">
               Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores iure, delectus minus facere similique laudantium praesentium! Neque eligendi consectetur quo repellendus ipsam sapiente mollitia optio quas pariatur perferendis. Hic, optio!
            </p>
            <div class="bg-light p-5 rounded">
               <h1>Thumbnail example</h1>
               <p class="lead">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis cumque aliquid et est labore eaque similique perferendis a quo, corrupti consequatur voluptate mollitia, voluptatum nihil. Nostrum nesciunt earum iusto eos?
               </p>
            </div>
            <br>
            <p>
               Lorem ipsum dolor sit amet consectetur adipisicing elit. At doloremque deserunt magnam nulla ab delectus, vero rem ad, corrupti qui iure rerum pariatur ea aperiam. Numquam aut ratione a autem.
            </p>
            <p>
               Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum perferendis fuga maxime, neque ipsum doloremque perspiciatis, praesentium quos incidunt doloribus odio! Pariatur cum fuga quos! Sit voluptatem pariatur perspiciatis hic!
            </p>
            <p>
               Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto dicta a, eius sapiente ea quaerat, sequi minus ipsa totam ratione adipisci fuga excepturi, dolores delectus placeat tempore. Incidunt, fuga praesentium?
            </p>
         </article>
         <br>
      </div>
      <div class="col-md-4">
         <?= $this->renderPartial('Shared/SideBar') ?>
      </div>
   </div>
</div>