<?= $this->layout('Shared/Layout') ?>
<?= $this->Inject('Formatter', \Application\Lib\Formatter::class) ?>

<div class="d-flex flex-column justify-content-center text-center" style="height: 250px; background-image: url(/images/113-800x200.jpg); background-size: cover;">
   <h1 class="text-info display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;">
      <h1 class="text-info display-2 mx-auto fw-normal" style="text-shadow: 2px 2px 8px #000;"><?= $model->Title ?></h1>
      <p class="lead w-75 mx-auto text-white fw-normal" style="text-shadow: 2px 2px 8px #000;">
         By <?= $model->Author->Name ?> | On <?= $model->EditedAt->format('j F Y') ?>
      </p>
</div>
<div class="container">
   <br><br>
   <div class="row">
      <div class="col-md-8">
         <article>
            <nav aria-label="breadcrumb">
               <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="/">Home</a></li>
                  <li class="breadcrumb-item"><a href="/home/blog">Blog</a></li>
                  <li class="breadcrumb-item active" aria-current="page"><?= $model->Title ?></li>
               </ol>
            </nav>
            <small class="text-muted">By <?= $model->Author->Name ?> | On February 23, 2019</small>
            <p class="fst-italic">
               Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores iure, delectus minus facere similique laudantium praesentium! Neque eligendi consectetur quo repellendus ipsam sapiente mollitia optio quas pariatur perferendis. Hic, optio!
            </p>
            <div class="bg-light p-5 rounded">
               <h1>Thumbnail example</h1>
               <p class="lead">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis cumque aliquid et est labore eaque similique perferendis a quo, corrupti consequatur voluptate mollitia, voluptatum nihil. Nostrum nesciunt earum iusto eos?
               </p>
            </div>
            <br>
            <p>
               Lorem ipsum dolor sit amet consectetur adipisicing elit. At doloremque deserunt magnam nulla ab delectus, vero rem ad, corrupti qui iure rerum pariatur ea aperiam. Numquam aut ratione a autem.
            </p>
            <p>
               Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum perferendis fuga maxime, neque ipsum doloremque perspiciatis, praesentium quos incidunt doloribus odio! Pariatur cum fuga quos! Sit voluptatem pariatur perspiciatis hic!
            </p>
            <p>
               Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto dicta a, eius sapiente ea quaerat, sequi minus ipsa totam ratione adipisci fuga excepturi, dolores delectus placeat tempore. Incidunt, fuga praesentium?
            </p>
            <aside>
               <div>
                  <h4>Comments</h4>
                  <form method="post" action="/user/comment/new/<?= $model->Id ?>">
                     <textarea class="form-control h-100" id="message" name="Message" placeholder="Your Comment *" onfocus="show(true)" required=""></textarea>
                     <div class="mt-2 text-end">
                        <button type="submit" class="btn btn-info text-white" id="send">Send</button>
                     </div>
                  </form>
                  <br>
                  <?php foreach (array_reverse($model->Comments->toArray()) as $comment) : ?>
                     <div class="row fs-6 lh-sm">
                        <div class="col-1">
                           <img class="img-fluid rounded-circle" src="<?= $comment->Author->Picture ?>" alt="">
                        </div>
                        <div class="col-11">
                           <p class="fs-6 lh-sm">
                              <b><?= $comment->Author->Name ?></b><span><small> | <?= $this->Formatter->formatDateDiff($comment->EditedAt) ?></small></span>
                              <br>
                              <small><?= $comment->Content ?></small>
                           </p>
                        </div>
                     </div>
                  <?php endforeach ?>
               </div>
            </aside>
         </article>
         <br>
      </div>
      <div class="col-md-4">
         <?= $this->renderPartial('Shared/Sidebar') ?>
      </div>
   </div>
</div>